stages:
  - build
  - test
  - push

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose -f docker-compose.yml build

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml run --rm catalog pytest

push:
  stage: push
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker-compose -f docker-compose.yml push
  only:
    - master
    - tags
