apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-db-pvc
  namespace: deployment-project
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce