apiVersion: v1
kind: PersistentVolume
metadata:
  name: catalog-db-pv
  namespace: deployment-project
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /home/docker/data/catalog-db-pv

